# PostgreSQL databases go in the databases section
databases:
  - name: ciso-db
    plan: free
    ipAllowList: [] # Allows internal connections only

services:
  # Django Backend Service
  - type: web
    name: backend
    runtime: docker
    plan: free
    region: oregon # Specify region to match database
    image:
      url: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    healthCheckPath: /api/build
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ciso-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: "False"

  # Huey Background Worker
  - type: worker
    name: huey
    runtime: docker
    plan: free
    region: oregon # Same region as database
    image:
      url: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    dockerCommand: "poetry run python manage.py run_huey -w 2"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ciso-db
          property: connectionString

  # Frontend Service
  - type: web
    name: frontend
    runtime: docker
    plan: free
    region: oregon # Same region as other services
    image:
      url: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    routes:
      - type: rewrite
        source: /api/*
        destination: https://backend-[your-hash].onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
