databases:
  - name: ciso-db
    plan: free
    postgresMajorVersion: "14"
    ipAllowList: []

services:
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/compliance-rehab/ciso-assistant-community.git
    branch: main
    rootDir: backend
    plan: free
    region: oregon
    healthCheckPath: /api/build
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ciso-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: "False"

  - type: worker
    name: huey
    runtime: docker
    repo: https://github.com/compliance-rehab/ciso-assistant-community.git
    branch: main
    rootDir: backend
    plan: free
    region: oregon
    dockerCommand: "poetry run python manage.py run_huey -w 2"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ciso-db
          property: connectionString

  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/compliance-rehab/ciso-assistant-community.git
    branch: main
    rootDir: frontend
    plan: free
    region: oregon
    envVars:
      - key: PUBLIC_BACKEND_API_URL
        value: "https://backend-RENDERHASH.onrender.com/api"
